services:

  orbslam3:
    image: rv_orbslam:humble
    ipc: host
    runtime: nvidia
    stop_signal: SIGINT
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XDG_RUNTIME_DIR=/tmp/runtime-root
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NO_AT_BRIDGE=1
      - BAG=
      - MODE=stereo-inertial
      - CAMERA=oak_pro_wide
      - DO_RECTIFY=false
      - FROM_BAG=0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/dri:/dev/dri
      # - ../../robot_vision_2025:/root/robot_vision_2025:rw
      - ../memory_register/orbslam_data/trajectory:/root/memory_register/orbslam_data/trajectory
      - ../memory_register/orbslam_data/map:/root/memory_register/orbslam_data/map
      - ../memory_register/oak:/root/memory_register/oak
      - ../memory_register/realsense:/root/memory_register/realsense
      - ../orbslam_setup/config:/root/orbslam_setup/config
    network_mode: host
    stdin_open: true
    tty: true