version: "2.3"
services:

  orbslam3:
    image: rv_orbslam:v1
    shm_size: '2gb'
    runtime: nvidia
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XDG_RUNTIME_DIR=/tmp/runtime-root
      - NO_AT_BRIDGE=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      # - BAG=realsense_stereo_2025-12-13_11-27-49
      - MODE=stereo
      - CAMERA=realsense
      - DO_RECTIFY=false
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/dri:/dev/dri
      - ../memory_register/orbslam_data/trajectory:/root/memory_register/orbslam_data/trajectory
      - ../memory_register/orbslam_data/map:/root/memory_register/orbslam_data/map
      - ../memory_register/oak:/root/memory_register/oak
      - ../memory_register/realsense:/root/memory_register/realsense
    network_mode: host
    stdin_open: true
    tty: true