version: "3.7"
services:

  orbslam3:
    image: rv_orbslam:v1
    shm_size: '2gb'
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XDG_RUNTIME_DIR=/tmp/runtime-root
      - BAG=realsense_stereo_2025-12-12_18-31-26
      - MODE=stereo
      - CAMERA=realsense
      - DO_RECTIFY=false
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../memory_register/orbslam_data/trajectory:/root/memory_register/orbslam_data/trajectory
      - ../memory_register/orbslam_data/map:/root/memory_register/orbslam_data/map
      - ../memory_register/oak:/root/memory_register/oak
      - ../memory_register/realsense:/root/memory_register/realsense
    network_mode: host
    stdin_open: true
    tty: true