version: "3"
services:

  realsense:
    image: rv_realsense:v1
    environment:
      - RECORD_BAG=0
      - MODE
    volumes:
      - ../memory_register/realsense:/root/memory_register/realsense
      - ../memory_register/orbslam_data:/root/memory_register/orb_slam_data
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
      - /dev/video2:/dev/video2
      - /dev/video3:/dev/video3
      - /dev/video4:/dev/video4
      - /dev/video5:/dev/video5
